# Generated by Django 2.2 on 2019-11-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_del_alojamiento', models.CharField(blank=True, max_length=150, null=True)),
                ('habitaciones_descripcion', models.TextField(blank=True, null=True)),
                ('banos_descripcion', models.TextField(blank=True, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=150, null=True)),
                ('ubicacion_url', models.URLField(blank=True, null=True)),
                ('imagen_1', models.URLField(blank=True, null=True)),
                ('imagen_2', models.URLField(blank=True, null=True)),
                ('imagen_3', models.URLField(blank=True, null=True)),
                ('imagen_4', models.URLField(blank=True, null=True)),
                ('imagen_5', models.URLField(blank=True, null=True)),
                ('imagen_6', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Alojamiento',
                'verbose_name_plural': 'Alojamientos',
            },
        ),
    ]
